### ISSUE TITLE
Fix fmin on windows

### ISSUE THREAD

**Issue by Keno** [Keno/julia#10]
I probably messed up with the macro in math.jl. Should be easy to fix

**Comment by Keno** [comment]
Turns out `fmin` and `fminf` are some of the many function of C99 that Microsoft chose not to implement :(. @ViralBShah (this should send you a notification, I hope) What's the status of openlibm? Can we use it to provide `fminf` and others that are not implemented on Windows?

**Comment by vtjnash** [comment]
(I played around a bit with openlibm before too helping Viral with some build errors). It looks like it may work (with several minor fixes due to missing headers). However, Windows does not define several functions on infinity (e.g. isinff) or defines them differently (it uses different values for the return constants), so it would take some work to make sure it is truly portable. However, we need to stop using the built-in definitions anyways for fpclassify, isinf, isnan, isnormal, and isfinite, since they aren't entirely correct on Mac or Ubuntu either.

I can push to the original repo or a fork if someone else want to take a look.

**Comment by Keno** [comment]
Hmm, can't we provide the proper functions that are missing? E.g. for isinff we would only need to check for the proper bit representation of the IEEE 754 float, which should not be too difficult using the union types declared by openlibm

**Comment by vtjnash** [comment]
Yes, we should be able to. I just want to make sure we don't accidentally leave a function around (like fpclassify) that is returning the incorrect answer just because it seems to compile fine.

It looks like isnan, isnormal, and isfinite are already defined. It's just fpclassify and isinf that need the most work. (and isnan has one necessary definition commented out)

**Comment by ViralBShah** [comment]
Making openlibm truly independent is a worthy goal by itself, and we can use it in julia instead of fdlibm as well. Also, we need the assembly implementations to build so that it is comparable on performance.

**Comment by ViralBShah** [comment]
Also, it may not be too difficult to convert all of openlibm to julia, but making it robust and complete may take a long time.

-viral

**Comment by vtjnash** [comment]
In the meantime, I've written isinf as loladiro suggested. It now builds on Windows as well as Mac and Linux and appears to integrate well with julia (that program is an awesome test environment for quickly scripting/testing c code :). I'm currently maintaining two branches at https://github.com/vtjnash/openlibm (inline and master).

Open issues with openlibm are: (1) fpclassify isn't written. (2) __strong_reference isn't defined (I'm uncertain what it is supposed to do and how -- I tried copying the header from a BSD machine, but it throws a compile error on Mac). (3) Building the inline branch throws errors (although Viral has previous suggested that the inline build doesn't save much execution time anyways). (4) more testing

However, I don't think any of these are critical enough (expect for perhaps the minimal testing) to stop you from using it to get fmin &etc.

**Comment by ViralBShah** [comment]
I've seen people swearing by inline, but in practice, I have often not seen any measurable difference in most cases I have tried. Also, feel free to push to the openlibm repo. Nobody is using it, so maybe simpler to develop directly on it.

Is __strong_reference one of those C99 things? Much of the complexity in the openlibm codebase is to deal with compilers, it seems.

-viral

**Comment by vtjnash** [comment]
I will, I was just using my fork as a way to manage the branches while I tested everything. I think it is a way of hiding stuff from the linker. It must not be C99 since it doesn't seem to really exist outside of BSD.

Apparently, reference = alias in GCC. This is the best site I've come across so far at explaining it: http://sourceware.org/ml/binutils/2005-10/msg00107.html

It seems to me that some of this doesn't matter much anyways if we are using it as a dynamic library, since we will be writing the appropriate wrapper code for the header anyways.
