### ISSUE TITLE
Align SIGINT behavior with that on UNIX

### ISSUE THREAD

**Issue by Keno** [Keno/julia#14]

**Comment by vtjnash** [comment]
We need to remove the sigint handler and use SetConsoleCtrlHandler(sigint_handler,1). I'm not sure what this issue is supposed to reference, but using signal(SIGINT) on Windows apparently runs the signal handler in a parallel thread. It should be a clean swap, I just haven't finished setting up my Julia build environment so I can't test it.

**Comment by Keno** [comment]
Right, I was just setting up issues for things we got on the mailing list to not keep tracking them. I'll do this once I'm done porting readline 6.2 to Windows (the last release for Windows was 5.0 which didn't have multiline support)

**Comment by Keno** [comment]
Apparently `SetConsoleCtrlHandler` runs in a separate thread to, so we can't directly call `jl_raise`. We'll have to come up with some solution that calls `jl_raise` from the main thread

**Comment by vtjnash** [comment]
I've got some code working that gives the correct behavior. However, Windows seems to be really bad about actually sending SIGINT most of the time. I'm not sure if this is related to the tty raw/cooked mode again, but we only get the signal while at the readline prompt. And while running in MingW's shell something else kills it a very short time later anyways (but cmd.exe is OK).

**Comment by vtjnash** [comment]
While MinGW's shell still kills julia unconditionally, the signal handling works correctly when run from cmd.com
